name: workflowList
on: push
jobs: 
  qualityCheck:
    name: quality-check
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
    - name: Install Dependencies
      run: yarn install
    - name: Install Dependencies
      run: npm run lint
    

